name: Revert merge commit
description: Revert last merge commit

runs:
  using: "composite"
  steps:
    - name: Branch out
      shell: bash
      run: |
        git checkout -b revert-${{ github.sha }} main
        
    - name: Revert last commit
      env:
        LAST_COMMIT: "${{ github.sha }}"
      shell: bash
      run: |
        last_merge_commit=$(git rev-list --merges --max-count=1 HEAD)
        if [[ "${LAST_COMMIT}" == "${last_merge_commit}" ]]
        then
          git revert -m 1 HEAD --no-edit
          echo "WAS MERGE"
          echo $last_merge_commit
        else
          git revert HEAD --no-edit
          echo "WAS NOT MERGE"
        fi
    
    - name: Push revert commit to feature branch
      shell: bash
      run: |
        git push origin revert-${{ github.sha }}

    - name: Create PR
      env: 
        GH_TOKEN: ${{ github.token }}
      shell: bash
      run: |
        gh pr create -f
        gh pr merge --auto -s